#!/usr/bin/env python
#encoding: utf-8

# Genmsg sources
genmsg_sources = [
        'genmsgParse.ly',
        'genmsgLex.re',
        'genmsgCode.c',
        'genmsgManual.c',
        'genmsg.c'
]

bld.program(
        source       = genmsg_sources,
        target       = 'genmsg',
        install_path = 'bin',
        use          = 'alticore_includes alticore_shlib'
)
