
test : comment os prep string typedef define

os :
	./accs < OS.h

comment :
	./accs < sample_comment.cpp

prep :
	./accs < sample_prep.cpp

string :
	./accs < sample_string.cpp

typedef :
	./accs < sample_typedef.cpp

define :
	./accs < sample_define.cpp

