

echo "LATCH POSIX TEST"; 
date
ALTIBASE_LATCH_TYPE=2
export ALTIBASE_LATCH_TYPE
testLatchFinal
date

echo "LATCH NATIVE TEST"; 
date
ALTIBASE_LATCH_TYPE=0
export ALTIBASE_LATCH_TYPE
ALTIBASE_LATCH_SPIN_COUNT=200000
export ALTIBASE_LATCH_SPIN_COUNT
testLatchFinal
date
