# Copyright 1999-2007, ALTIBASE Corporation or its subsidiaries.
# All rights reserved.

# $Id: Makefile 11299 2010-06-21 01:19:28Z djin $
#

include ../../../makefiles/root.mk
include $(CORE_DIR)/core.mk


OBJ_TARGETS      = act_objs
SHOBJ_TARGETS    = act_shobjs

act_objs_SRCS    = $(ACT_SRCS)
act_shobjs_SRCS  = $(ACT_SRCS)


DEFINES         += ACP_CFG_DL_EXPORT


include $(MAKEFILES_DIR)/rule.mk
