ALTER SESSION SET EXPLAIN PLAN = ON;
ALTER SYSTEM SET TRCLOG_EXPLAIN_GRAPH = 1;

SET TIMING ON;
SET TIMESCALE MILSEC;

SELECT PS_PARTKEY,
       SUM(PS_SUPPLYCOST * PS_AVAILQTY) AS VALUE
FROM PARTSUPP,
     SUPPLIER,
     NATION
WHERE PS_SUPPKEY = S_SUPPKEY
      AND S_NATIONKEY = N_NATIONKEY
      AND N_NAME = 'GERMANY'
GROUP BY PS_PARTKEY 
HAVING SUM(PS_SUPPLYCOST * PS_AVAILQTY) > 
       ( SELECT	SUM(PS_SUPPLYCOST * PS_AVAILQTY) * 0.0001 
         FROM PARTSUPP,
              SUPPLIER,
              NATION
         WHERE PS_SUPPKEY = S_SUPPKEY
           AND S_NATIONKEY = N_NATIONKEY
           AND N_NAME = 'GERMANY' )
ORDER BY VALUE DESC;

ALTER SYSTEM SET TRCLOG_EXPLAIN_GRAPH = 0;
