ALTER SESSION SET EXPLAIN PLAN = ON;
--ALTER SYSTEM SET TRCLOG_EXPLAIN_GRAPH = 1;

SET TIMING ON;
SET TIMESCALE MILSEC;
SELECT SUM(L_EXTENDEDPRICE) / 7.0 AS AVG_YEARLY
FROM LINEITEM,
     PART
WHERE P_PARTKEY = L_PARTKEY
      AND P_BRAND = 'Brand#23'
      AND P_CONTAINER = 'MED BOX'
      AND L_QUANTITY < ( SELECT 0.2 * AVG(L_QUANTITY)
                         FROM LINEITEM
                         WHERE L_PARTKEY = P_PARTKEY );


ALTER SYSTEM SET TRCLOG_EXPLAIN_GRAPH = 0;
