#define GENMSG_TOKEN_SECTION                         1
#define GENMSG_TOKEN_FILE                            2
#define GENMSG_TOKEN_SEMICOLON                       3
#define GENMSG_TOKEN_ERROR                           4
#define GENMSG_TOKEN_LOG                             5
#define GENMSG_TOKEN_PRODUCT_ID                      6
#define GENMSG_TOKEN_ASSIGN                          7
#define GENMSG_TOKEN_NUMBER                          8
#define GENMSG_TOKEN_PRODUCT_NAME                    9
#define GENMSG_TOKEN_STRING                         10
#define GENMSG_TOKEN_PRODUCT_ABBR                   11
#define GENMSG_TOKEN_LANGUAGES                      12
#define GENMSG_TOKEN_COMMA                          13
#define GENMSG_TOKEN_IDENTIFIER                     14
#define GENMSG_TOKEN_BRACE_OPEN                     15
#define GENMSG_TOKEN_BRACE_CLOSE                    16
#define GENMSG_TOKEN_ERR_ID                         17
#define GENMSG_TOKEN_KEY                            18
#define GENMSG_TOKEN_MSG                            19
