CREATE OR REPLACE VIEW ADM_SEQ  AS
SELECT A.TABLE_NAME,
       B.CURR_VALUE,
       B.START_VALUE,
       B.INCREMENT_VALUE,
       B.CACHE_VALUE,
       B.MAX_VALUE,
       B.MIN_VALUE, B.IS_CYCLE
FROM SYSTEM_.SYS_TABLES_ A,
     SYSTEM_.SYSX_SEQUENCE_ B
WHERE A.TABLE_OID = B.TABLE_OID;

