/**
 *  Copyright (c) 1999~2017, Altibase Corp. and/or its affiliates. All rights reserved.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License, version 3,
 *  as published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Altibase_jdbc_driver_JniExt */

#ifndef _Included_Altibase_jdbc_driver_JniExt
#define _Included_Altibase_jdbc_driver_JniExt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Altibase_jdbc_driver_JniExt
 * Method:    getTcpiLastDataRecv
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_Altibase_jdbc_driver_JniExt_getTcpiLastDataRecv
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
