include ../../pdEnv.mk

DIRS	= #cygipc-2.00 pthread

.PHONY: $(DIRS)
$(DIRS):
	$(MAKE) -C $@ $(SUBDIR_TARGET)

all:
#	make $(S) $(DIRS) SUBDIR_TARGET=all
ofiles:
#	make $(S) $(DIRS) SUBDIR_TARGET=all
clean:
#	make $(S) $(DIRS) SUBDIR_TARGET=clean
