# Copyright 1999-2007, ALTIBASE Corporation or its subsidiaries.
# All rights reserved.

# $Id: Makefile 893 2007-09-27 13:01:34Z shsuh $
#

include ../../../../makefiles/root.mk
include $(CORE_DIR)/core.mk

SUBDIRS = src 

include $(MAKEFILES_DIR)/rule.mk
