# Copyright 1999-2007, ALTIBASE Corporation or its subsidiaries.
# All rights reserved.

# $Id:
#

ALTICORE_MAJOR_VERSION  = 1
ALTICORE_MINOR_VERSION  = 3
ALTICORE_TERM_VERSION  = 10
ALTICORE_PATCH_VERSION  = 0
ALTICORE_VERSION        = $(ALTICORE_MAJOR_VERSION).$(ALTICORE_MINOR_VERSION).$(ALTICORE_TERM_VERSION).$(ALTICORE_PATCH_VERSION)
